version: "3.8"

services:
  db:
    image: postgres:15
    container_name: fastapi_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app/app  # for hot reload (optional)
    restart: always
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env

volumes:
  postgres_data:
